---
title: "GCaMPx Evaluations"
author: "Aaron"
date: "April 15, 2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require('hdf5r')
require('nat')
require("magick")
require('ggplot2')
require('squash')
require('digest')
require("viridis")
require('signal')

LSMCodeRConfig=list(srcdir="C:/Users/Aaron/Documents/R/LSMCodeR")
LSMCodeRConfig$scriptsMain<-file.path(LSMCodeRConfig$srcdir,"scripts_main")
LSMCodeRConfig$scriptsUtility<-file.path(LSMCodeRConfig$srcdir,"scripts_utility")
LSMCodeRConfig$functions<-file.path(LSMCodeRConfig$srcdir,"functions")
LSMCodeRConfig$logDir <- file.path(LSMCodeRConfig$srcdir,"logs")
LSMCodeRConfig$protocolDir <- file.path(LSMCodeRConfig$srcdir,"protocolCSVs")

source(file.path(LSMCodeRConfig$functions,"calciumImagingFunctions.R"))

pixelOffset=399
protocolList <- list(
  sabineProtocolSimple = list(
    presentationMatrix = matrix(rep(c(3,4,5,6),5),nrow = 5,byrow=TRUE),
    stimulationSections = read.csv(file.path(LSMCodeRConfig$protocolDir,"sabineProtocolSimple")),
    framesSkipped = 30000
  )
)

if (dir.exists("F:\\Imaging\\GCaMP7_tests\\20181204-g7")) {
  print("Setting imageDir to F:/Imaging/GCaMP7_tests/20181204-g7")
  imageDir <- "F:/Imaging/GCaMP7_tests/20181204-g7"
} else if (dir.exists("/Volumes/TranscendJD/Work/")) {
  print("Setting imageDir to /Volumes/TranscendJD/Work/")
  imageDir <- "/Volumes/TranscendJD/Work/"
} else {
  print("Please set the variable 'imageDir' to something sensible.")
}

tectumROIs <- read.csv(file.path(LSMCodeRConfig$srcdir,"stuff","tectumROI.csv"))
fishGenos <- read.csv(file.path(LSMCodeRConfig$srcdir,"models","DSLM-fish.csv"))
fishGenos$Date <- as.character(as.Date(fishGenos$Date,format='%d.%m.%Y'))

genotypeOrder <- c("6s","6f EF05","7f","7f EF05","7b","7b EF05")
```


```{r roiBasedAnalysis, include=FALSE}
source(file.path(LSMCodeRConfig$scriptsMain,"roiBasedAnalysis.R"),echo = FALSE)
```

Having done the heavy lifting, one can now start to evaluate the data.
These analysis are similar to what is being done in analysis.R.

```{r loadAnalysis, cache = FALSE, include=FALSE}
completedMats <- dir(file.path(LSMCodeRConfig$srcdir,"objects"),patt=".mat",full=T)
completedMats.clean <- completedMats[!substr(basename(completedMats),1,3)%in%fishGenos$Fish[fishGenos$Use=="No"]]

completedMats.list <- list()
for (mats in completedMats.clean) {
  # print(substr(basename(mats),1,4))
  # print(names(readRDS(mats)))
  completedMats.list[[substr(basename(mats),1,4)]] <- readRDS(mats)
}

fishGenos <- read.csv(file.path(LSMCodeRConfig$srcdir,"models","DSLM-fish.csv"))
fishFullGeno <- c()
for (i in unique(substr(names(completedMats.list),1,3))){
  fishFullGeno <- c(fishFullGeno,as.character(unique(fishGenos[fishGenos$Fish==i,"Full_geno"])))
}
names(fishFullGeno) <- unique(substr(names(completedMats.list),1,3))

analysisDF <- readRDS(file=file.path(LSMCodeRConfig$srcdir,"objects",paste("analysisDF",".RDS",sep="")))
if ( length(unique(as.character(analysisDF$animal))) != length(completedMats.list) ) {
  print("remaking analysisDF")
  analysisDF <- c()
  for (k in 1:length(completedMats.list)){
    analysisDF.animals <- c()
    animal <- names(completedMats.list[k])
    cat("",sep="\n")
    print(paste("animal:",animal))
    for (j in 1: length(completedMats.list[[k]][[1]])){
      analysisDF.stimulus <- c()
      stimulus <- substr(names(completedMats.list[[k]][[1]][j]),
                         nchar(names(completedMats.list[[k]][[1]][j]))-2,
                         nchar(names(completedMats.list[[k]][[1]][j])))
      # print(paste("stimulus:",stimulus))
      for (i in 1:length(completedMats.list[[k]][[1]][[j]])) {
        analysisDF.zplane <- c()
        z_plane <- names(completedMats.list[[k]][[1]][[j]][i])
        # print(paste("z_plane:",z_plane))
        cat(".")
        analysisDF.zplane <- 
          completedMats.list[[k]][[1]][[j]][[i]][,c("snr.mean","background.mean","dff.mean","snr.max","dff.max")]
        analysisDF.zplane$z_plane <- as.factor(z_plane)
        analysisDF.stimulus <- rbind(analysisDF.stimulus,analysisDF.zplane)
      }
      analysisDF.stimulus$stimulus <- as.factor(stimulus)
      analysisDF.animals <- rbind(analysisDF.animals,analysisDF.stimulus)
    }
    analysisDF.animals$animal <- as.factor(animal)
    analysisDF.animals$date <- fishGenos[k,"Date"]
    analysisDF.animals$laser <- fishGenos[k,"Laser"]
    analysisDF.animals$use <- fishGenos[k,"Use"]
    analysisDF <- rbind(analysisDF,analysisDF.animals)
  }
  
}



for (fish in 1:length(fishFullGeno)) {
  analysisDF$geno[substr(analysisDF$animal,1,3)==names(fishFullGeno[fish])] <- fishFullGeno[fish]
}
analysisDF$geno <- as.factor(analysisDF$geno)
saveRDS(analysisDF,file=file.path(LSMCodeRConfig$srcdir,"objects",paste("analysisDF",".RDS",sep="")))
```


If I want to show how the individual animals stack up, rather than showing every single data point,
I can get averages of each animal and plot them.

```{r dff.max by animal, include=FALSE, cache=T}

summaryDF.noZeros <- data.frame(dff.mean=double(),
                                background.mean=double(),
                                snr.mean=double(),
                                geno=character(),
                                animalKey=character()
)

countingDF <- data.frame(animal=character(),
                         geno=character())

animals2=unique(substr(unique(analysisDF$animal),1,3))

for (animal in animals2){
  tempDF.animals <- analysisDF[grepl(paste("^",animal,sep=""),analysisDF$animal),]
  tempDF.animals.subset <- subset(tempDF.animals,
                                  background.mean>20 &
                                    dff.max!=0)
  if (nrow(tempDF.animals.subset)>0) {
    tempSummary=data.frame(dff.mean=mean(tempDF.animals.subset$dff.max[is.finite(tempDF.animals.subset$dff.max)]),
                           background.mean=mean(tempDF.animals.subset$background.mean[
                             is.finite(tempDF.animals.subset$background.mean)
                             ]),
                           snr.mean=mean(tempDF.animals.subset$snr.max[is.finite(tempDF.animals.subset$snr.max)]),
                           geno=unique(tempDF.animals.subset$geno),
                           animalKey=animal)
    
    summaryDF.noZeros <- rbind(summaryDF.noZeros,tempSummary)
    countingDF <- rbind(countingDF,
                        data.frame(animal=animal,
                                   geno=unique(summaryDF.noZeros[summaryDF.noZeros$animalKey==animal,"geno"]))
                        )
    
  }
  
}

# AAMA has some strange artifacts that cause it to be pretty weird, so I think it's safe to drop it
# Also, we don't need to include iGABASnFr for this analysis
summaryDF.noZeros <- subset(summaryDF.noZeros,animalKey!="AAM" & geno!="iGABASnFr")

```

```{r plots}
ggplot(data = subset(countingDF,geno!="iGABASnFr")) + 
  geom_histogram(aes(geno),stat="count") + 
  scale_y_continuous(breaks = seq(0, 20)) +
  scale_x_discrete(limits=genotypeOrder)

ggplot(summaryDF.noZeros,
       aes(geno,dff.mean)) + 
  geom_boxplot(notch = F) +
  geom_jitter(aes(color=animalKey)) + scale_colour_viridis_d(option="D",aesthetics = "colour") +
  scale_x_discrete(limits=genotypeOrder)

pairwise.wilcox.test(x = summaryDF.noZeros$dff.mean, 
                     g = summaryDF.noZeros$geno, 
                     p.adjust.method = "bonferroni")

ggplot(summaryDF.noZeros,
       aes(geno,snr.mean)) + 
  geom_boxplot(notch = F) +
  geom_jitter(aes(color=animalKey)) + scale_colour_viridis_d(option="C",aesthetics = "colour") +
  scale_x_discrete(limits=genotypeOrder)

pairwise.wilcox.test(x = summaryDF.noZeros$snr.mean, 
                     g = summaryDF.noZeros$geno, 
                     p.adjust.method = "bonferroni")

```


```{r cumulative sum of dFF data, include=FALSE, cache=TRUE}
animals <- unique(substr(analysisDF$animal,1,3))
percentDF <- data.frame()
for (animal in animals) {
  animalAnalysisDF2 <- analysisDF[grepl(paste("^",animal,sep=""),analysisDF$animal),]
  animalAnalysisDF2 <- animalAnalysisDF2[is.finite(animalAnalysisDF2$dff.max) & 
                                           animalAnalysisDF2$background.mean > quantile(animalAnalysisDF2$background.mean)["25%"] &
                                           animalAnalysisDF2$dff.max!=0,]
  percents <- quantile(animalAnalysisDF2$dff.max,probs = seq(0,1,.01),names = FALSE,na.rm = TRUE)
  percent.cumsum <- cumsum(percents)/max(cumsum(percents))
  

    
  tempDF <- data.frame(PercentdFF=percents,
                       cumsum=percent.cumsum,
                       percentile=c(0:100),
                       animal=animal,
                       genotype=unique(animalAnalysisDF2$geno))
  percentDF <- rbind(percentDF,tempDF)
}

genotypes=as.character(unique(percentDF$genotype))
averageDFF <- data.frame()
for (genotype in genotypes){
  genos=percentDF[percentDF$genotype==genotype,]
  animals=as.character(unique(genos$animal))
  averageDFF.wide <- data.frame(percentile=c(0:100))
  for (animal in animals) {
    averageDFF.wide <- cbind(averageDFF.wide,genos[genos$animal==animal,"PercentdFF"])
    means <- c()
    SDs <- c()
    for (row in 1:nrow(averageDFF.wide)) {
      means <- c(means,mean(unlist(averageDFF.wide[row,c(2:length(averageDFF.wide))])))
      SDs <- c(SDs,sd(unlist(averageDFF.wide[row,c(2:length(averageDFF.wide))])))
    }
    averageDFF.long <- data.frame(percentile=c(0:100),
                                  means=means,
                                  SDs=SDs,
                                  genotype=genotype)
  }
  averageDFF <- rbind(averageDFF,averageDFF.long)
}


```

```{r cum sum plot}
ggplot(data=averageDFF[averageDFF$genotype!="iGABASnFr",],
       aes(x=means,y=percentile)) + 
  geom_point(aes(color=genotype)) + 
  xlim(c(0,5)) +
  xlab("Average dF/F") + ylab("Normalized Percentage of Maximum dF/F") 

```


```{r cumSum SNR, include=FALSE, cache=TRUE}
animals <- unique(substr(analysisDF$animal,1,3))
percentDF.snr <- data.frame()
for (animal in animals) {
  animalAnalysisDF2 <- analysisDF[grepl(paste("^",animal,sep=""),analysisDF$animal),]
  animalAnalysisDF2 <- animalAnalysisDF2[animalAnalysisDF2$background.mean > 
                                           quantile(animalAnalysisDF2$background.mean)["25%"],]
  percents <- quantile(animalAnalysisDF2$snr.max,probs = seq(0,1,.01),names = FALSE,na.rm = TRUE)
  percent.cumsum <- cumsum(percents)/max(cumsum(percents))
  
  
  
  tempDF <- data.frame(percentDF.snrF=percents,
                       cumsum=percent.cumsum,
                       percentile=c(0:100),
                       animal=animal,
                       genotype=unique(animalAnalysisDF2$geno))
  percentDF.snr <- rbind(percentDF.snr,tempDF)
}

genotypes=as.character(unique(percentDF.snr$genotype))
averageSNR <- data.frame()
for (genotype in genotypes){
  genos=percentDF.snr[percentDF.snr$genotype==genotype,]
  animals=as.character(unique(genos$animal))
  averageSNR.wide <- data.frame(percentile=c(0:100))
  for (animal in animals) {
    averageSNR.wide <- cbind(averageSNR.wide,genos[genos$animal==animal,"percentDF.snrF"])
    means <- c()
    SDs <- c()
    for (row in 1:nrow(averageSNR.wide)) {
      means <- c(means,mean(unlist(averageSNR.wide[row,c(2:length(averageSNR.wide))])))
      SDs <- c(SDs,sd(unlist(averageSNR.wide[row,c(2:length(averageSNR.wide))])))
    }
    averageSNR.long <- data.frame(percentile=c(0:100),
                                  means=means,
                                  SDs=SDs,
                                  genotype=genotype)
  }
  averageSNR <- rbind(averageSNR,averageSNR.long)
}

```

```{r cumSum SNR plots}
ggplot(data=averageSNR[averageSNR$genotype!="iGABASnFr",],
       aes(x=means,y=percentile)) + 
  geom_point(aes(color=genotype)) + 
  xlim(c(0,10)) +
  xlab("Average SNR") + ylab("Normalized Percentage of Maximum SNR")
```


```{r averageTraces}
animalAverageTraces <- readRDS(file=file.path(LSMCodeRConfig$srcdir,"objects","animalAverageTraces.RDS"))
animalAverageTraces$genotype <- factor(animalAverageTraces$genotype,levels = genotypeOrder)

ggplot(data=animalAverageTraces,aes(x = time,y = trailAverage)) + geom_smooth(aes(color=animalTrial)) + geom_smooth(color="black",lwd=1.3) + theme(legend.position = "none") + facet_wrap(~genotype,ncol=2)

ggplot(data=animalAverageTraces,aes(x = time,y = trailAverage)) + geom_smooth(aes(color=genotype))

animalAverageTracesByAnimalNotROI <- readRDS(file=file.path(LSMCodeRConfig$srcdir,
                                                            "objects","animalAverageTracesByAnimalNotROI.RDS")
                                             )
animalAverageTracesByAnimalNotROI$genotype <- factor(animalAverageTracesByAnimalNotROI$genotype,levels = genotypeOrder)
ggplot(data=newDF.big,aes(x=time,y=average)) + geom_smooth(aes(color=genotype)) + xlab("Time (seconds)") + ylab("dF/F")

```


Controls 
=== 

```{r LAZERS!}
tempDF.animals <- analysisDF[grepl(paste("^","AAB",sep=""),analysisDF$animal),]
ggplot(data = tempDF.animals,aes(background.mean,dff.max)) + geom_jitter(aes(color=as.factor(laser))) +
  labs(color = "Laser (%)") + ggtitle("Animal AAB imaged at 3 and 5% laser power")
```

```{r summary statistics, include=FALSE}
summaryDF.noZeros <- data.frame(dff.mean=double(),
                                background.mean=double(),
                                snr.mean=double(),
                                geno=character(),
                                date=character(),
                                animalKey=character()
)

animals2=unique(substr(unique(analysisDF$animal),1,3))

for (animal in animals2){
  tempDF.animals <- analysisDF[grepl(paste("^",animal,sep=""),analysisDF$animal),]
  tempDF.animals.subset <- subset(tempDF.animals,
                                  background.mean>20 &
                                    dff.max!=0)
  
  
  
  if (nrow(tempDF.animals.subset)>0) {
    print(paste(animal,unique(tempDF.animals.subset$date)))
    tempSummary=data.frame(dff.mean=mean(tempDF.animals.subset$dff.max[is.finite(tempDF.animals.subset$dff.max)]),
                           background.mean=mean(tempDF.animals.subset$background.mean[is.finite(tempDF.animals.subset$background.mean)]),
                           snr.mean=mean(tempDF.animals.subset$snr.max[is.finite(tempDF.animals.subset$snr.max)]),
                           geno=unique(tempDF.animals.subset$geno),
                           date=unique(tempDF.animals.subset$date),
                           animalKey=animal)
    
    summaryDF.noZeros <- rbind(summaryDF.noZeros,tempSummary)
  }
  
}

```


```{r plot by date}
ggplot(subset(summaryDF.noZeros, summaryDF.noZeros$animalKey!="AAM" & geno!="iGABASnFr"),
       aes(geno,dff.mean)) + 
  geom_boxplot(notch = F) + 
  geom_point(aes(color=animalKey)) + 
  facet_wrap(~date) +
  theme(legend.position = "none", axis.text.x = element_text(angle = 60, hjust = 1) ) +
  scale_x_discrete(limits=genotypeOrder)

ggplot(summaryDF.noZeros,
       aes(geno,dff.mean)) + 
  geom_boxplot(notch = F) +
  geom_jitter(aes(color=date)) +
  scale_x_discrete(limits=genotypeOrder)


```

